title: Jacquelyn Coleman
url:  http://127.0.0.1:4000
baseurl: 

author: Jacquelyn Coleman
description: Northern California Watercolorist.

include: ['_pages']

collections_dir: series

collections:
  home:
    output: true
  ocean:
    output: false
  landscape:
    output: false
  portraits:
    output: false
  still_life:
    output: false

markdown: kramdown
kramdown:
  input: GFM
