title: Jacquelyn Coleman
url: https://jacquelyn27.github.io/
baseurl: 

author: jacquelyn Coleman
description: Northern California watercolorist.

include: ['_pages']

collections:
  home:
    output: false
  gallery:
    output: false

markdown: kramdown
kramdown:
  input: GFM
